
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RBRACK = 17;
  public static final int TIMES = 5;
  public static final int ELSE = 14;
  public static final int PLUS = 3;
  public static final int RPAREN = 8;
  public static final int CHAR = 23;
  public static final int SEMI = 2;
  public static final int WHILE = 15;
  public static final int GREATEROREQUALTHAN = 32;
  public static final int LBRACK = 16;
  public static final int RCURLY = 13;
  public static final int LESSOREQUALTHAN = 31;
  public static final int IF = 11;
  public static final int LPAREN = 7;
  public static final int ID = 28;
  public static final int OF = 18;
  public static final int EQUALSEQUALS = 33;
  public static final int BOOLEAN = 24;
  public static final int LCURLY = 12;
  public static final int NOTEQUALS = 34;
  public static final int STRING = 25;
  public static final int EQUALS = 9;
  public static final int FLOAT = 22;
  public static final int LESSTHAN = 30;
  public static final int NUMBER = 27;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int MINUS = 4;
  public static final int PRINT = 10;
  public static final int error = 1;
  public static final int INTEGER = 21;
  public static final int FOR = 19;
  public static final int ARRAY = 26;
  public static final int TO = 20;
  public static final int GREATERTHAN = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "EQUALS",
  "PRINT",
  "IF",
  "LCURLY",
  "RCURLY",
  "ELSE",
  "WHILE",
  "LBRACK",
  "RBRACK",
  "OF",
  "FOR",
  "TO",
  "INTEGER",
  "FLOAT",
  "CHAR",
  "BOOLEAN",
  "STRING",
  "ARRAY",
  "NUMBER",
  "ID",
  "GREATERTHAN",
  "LESSTHAN",
  "LESSOREQUALTHAN",
  "GREATEROREQUALTHAN",
  "EQUALSEQUALS",
  "NOTEQUALS"
  };
}

